---
title: "system-huddle-email"
output: html_document
---


```{r setup, include=FALSE}

library(blastula)
library(rmarkdown)
library(here)
library(glue)
library(lubridate)
```


```{r processing, include = FALSE}

# source("Scripts/pull_and_process_monthly.R", local = knitr::knit_global())
```

```{r pressure, echo=FALSE}

sending_date <-
  paste0(
    format(Sys.Date() %m+% days(1), "%B "),
    format(Sys.Date() %m+% days(1), "%d") %>% as.numeric(),
    ", ",
    format(Sys.Date() %m+% days(1), "%Y")
  )


email_credential_location <- "/SharedDrive/deans/Presidents/HSPI-PM/Operations Analytics and Optimization/Administrative/Workgroups/R Workbench/Working Area/Data Connections/email_creds"
cc_list <- c("soyoun.kweon@mssm.edu",
             "leonarda.parente@mountsinai.org",
             "riya.navlani@mountsinai.org")
send_list <- c("soyoun.kweon@mssm.edu",
             "leonarda.parente@mountsinai.org",
             "riya.navlani@mountsinai.org")

# send_list <- c("Raul.Aguilar@mountsinai.org",
#                "Christina.Bogie-claxton@mountsinai.org",
#                "Kelly.Cassano@mountsinai.org",
#                "Abigail.Chen@mountsinai.org",
#                "Lucy.Chen@mountsinai.org",
#                "Kristen.Cittadino@mountsinai.org",
#                "Marcy.Cohen@mountsinai.org",
#                "sarah.curtis@mountsinai.org",
#                "Elvis.DeLeon@mountsinai.org",
#                "Guitree.Dhanraj@mountsinai.org",
#                "anne.dickerson@mountsinai.org",
#                "Amanda.Diresta@mountsinai.org",
#                "Oladapo.Durojaiye@mountsinai.org",
#                "Berthe.Erisnor@mountsinai.org",
#                "Sivan.Ertel@mountsinai.org",	
#                "Steve.Garcia@mountsinai.org",	
#                "alicia.gresham@mssm.edu",
#                "Jeffrey.Gurkin-young@mountsinai.org",
#             	 "luis.isola@mountsinai.org",
#             	 "anita.jaikaran@mssm.edu",
#             	 "Josiah.James@mountsinai.org",
#             	 "Christina.Joseph@mountsinai.org",
#             	 "Viola.Koxhaj@mountsinai.org",
#             	 "Mark.Liu@mountsinai.org",
#             	 "toni.mailly@mountsinai.org",
#             	 "Adrin.Mammen@mountsinai.org",
#             	 "lisa.mazie@mountsinai.org",
#             	 "Bellinger.Moye@mountsinai.org",
#             	 "amy.nelson@mountsinai.org",
#             	 "Ellie.Park@mountsinai.org",
#             	 "Lenisha.Pinckney@mountsinai.org",
#             	 "Zaleena.Rafick@mountsinai.org",
#             	 "Deirdre.Rosado@mountsinai.org",
#             	 "darlene.sanchez@mountsinai.org",
#             	 "Sangyoon.Shin@mountsinai.org",
#             	 "Jemilat.Siju@mountsinai.org",
#             	 "cardinale.smith@mssm.edu",
#             	 "Tonya.Tolliver@mountsinai.org",
#             	 "ania.wajnberg@mountsinai.org",
#             	 "jenny.waltzer@mountsinai.org",
#             	 "ricardo.yanes@mountsinai.org",
#             	 "Jessica.Zimmerman@mountsinai.org",
#             	 "Paul.Zucker@mountsinai.org")
email_subject <- glue("System Huddle Report - Week of {sending_date}")

sinai_logo <- add_image(file = "www/Mount_Sinai_Logo_H.png",
                        width = 300)

# Generate the footer text
footer_text <- glue("System Huddle Report for the Week of {sending_date}.")



##Use blastula to construct email to send
compose_email(header = sinai_logo,
              body = render_email("Scripts/email_body.Rmd")$html_html,
              footer = footer_text) %>%
  add_attachment(
    file = "/nfs/data/Applications/Ambulatory/system_huddle_test.html",
    filename = paste0("System Huddle Report_",format(Sys.Date()+1, "%m%d%y"),".html")) %>%                
  purrr::list_modify(html_str =
                       .$html_str %>%
                       stringr::str_replace_all(pattern = "(?i)#f6f6f6",
                                                replacement = "#FFFFFF")) %>%
  smtp_send(
    from = "soyoun.kweon@mssm.edu",
    to = send_list,
    cc = cc_list,
    credentials = creds_file(file = email_credential_location),
    subject = email_subject
  ) 

```